export const moduleCategories = {
  Accounts: "Accounts",
  "Employee Onboarding": "HR & Management",
  "Employee KYC": "HR & Management",
  "Customer KYC": "Customer KYC",
  "Import - DSR": "Import",
  Documentation: "Import",
  Submission: "Import",
  "Import - Operations": "Import",
  "Import - DO": "Import",
  "e-Sanchit": "Import",
  "LR Report": "SRCC",
  "Inward Register": "Inward and Outward Register",
  "Outward Register": "Inward and Outward Register",
  "Exit Feedback": "HR & Management",
  "Tyre Maintenance": "SRCC",
  "SRCC Directories": "SRCC",
  RTO: "SRCC",
  Export: "Export",
};
